Repository ES2-UFPI/m-Gym, pull requests merged in 2025-06, with the labels that each got.

#74 Pedro#52
  backend/src/__pycache__/auth.cpython-313.pyc
  backend/src/__pycache__/database.cpython-313.pyc
  backend/src/__pycache__/server.cpython-313.pyc
  backend/src/init_db.py
  backend/src/models/__init__.py
  backend/src/models/__pycache__/__init__.cpython-313.pyc
  backend/src/models/__pycache__/challenge.cpython-313.pyc
  backend/src/models/__pycache__/challengecompletion.cpython-313.pyc
  backend/src/models/__pycache__/profile.cpython-313.pyc
  backend/src/models/__pycache__/user.cpython-313.pyc
  backend/src/models/challenge.py
  backend/src/models/challengecompletion.py
  backend/src/models/user.py
  backend/src/schemas/__pycache__/user.cpython-313.pyc
  backend/src/schemas/challenge.py
  backend/src/schemas/challengecomplete.py
  m-gym.db
Labels: enhancement

#83 Validação de Campos concluída Close#55
  backend/src/__pycache__/auth.cpython-313.pyc
  backend/src/__pycache__/database.cpython-313.pyc
  backend/src/__pycache__/server.cpython-313.pyc
  backend/src/models/__pycache__/__init__.cpython-313.pyc
  backend/src/models/__pycache__/challenge.cpython-313.pyc
  backend/src/models/__pycache__/challengecompletion.cpython-313.pyc
  backend/src/models/__pycache__/profile.cpython-313.pyc
  backend/src/models/__pycache__/user.cpython-313.pyc
  backend/src/schemas/__pycache__/challenge.cpython-313.pyc
  backend/src/schemas/__pycache__/user.cpython-313.pyc
  frontend/src/CreateChallenge.js
  m-gym.db
Labels: enhancement, good first issue

#88 Pedro bug deploy
  backend/src/__pycache__/auth.cpython-313.pyc
  backend/src/__pycache__/database.cpython-313.pyc
  backend/src/__pycache__/server.cpython-313.pyc
  backend/src/models/__pycache__/__init__.cpython-313.pyc
  backend/src/models/__pycache__/challenge.cpython-313.pyc
  backend/src/models/__pycache__/challengecompletion.cpython-313.pyc
  backend/src/models/__pycache__/profile.cpython-313.pyc
  backend/src/models/__pycache__/user.cpython-313.pyc
  backend/src/schemas/__pycache__/challenge.cpython-313.pyc
  backend/src/schemas/__pycache__/user.cpython-313.pyc
  backend/src/server.py
  frontend/.env.development
  frontend/.env.production
  frontend/src/Inicio.js
Labels: bug

#91 Felipe#61#62#63
  backend/src/__pycache__/auth.cpython-313.pyc
  backend/src/__pycache__/database.cpython-313.pyc
  backend/src/__pycache__/server.cpython-313.pyc
  backend/src/models/__pycache__/__init__.cpython-313.pyc
  backend/src/models/__pycache__/challenge.cpython-313.pyc
  backend/src/models/__pycache__/challengecompletion.cpython-313.pyc
  backend/src/models/__pycache__/profile.cpython-313.pyc
  backend/src/models/__pycache__/user.cpython-313.pyc
  backend/src/schemas/__pycache__/challenge.cpython-313.pyc
  backend/src/schemas/__pycache__/user.cpython-313.pyc
  backend/src/server.py
  frontend/src/Inicio.js
  m-gym.db
Labels: enhancement

#92 model criado, considerando string de treino, foto e comentários close #65
  backend/src/models/__init__.py
  backend/src/models/activity.py
  backend/src/models/challenge.py
  backend/src/models/user.py
  backend/src/schemas/activity.py
Labels: enhancement

#95 Felipe#62
  backend/src/__pycache__/auth.cpython-313.pyc
  backend/src/__pycache__/database.cpython-313.pyc
  backend/src/__pycache__/server.cpython-313.pyc
  backend/src/models/__pycache__/__init__.cpython-313.pyc
  backend/src/models/__pycache__/activity.cpython-313.pyc
  backend/src/models/__pycache__/challenge.cpython-313.pyc
  backend/src/models/__pycache__/challengecompletion.cpython-313.pyc
  backend/src/models/__pycache__/profile.cpython-313.pyc
  backend/src/models/__pycache__/user.cpython-313.pyc
  backend/src/schemas/__pycache__/activity.cpython-313.pyc
  backend/src/schemas/__pycache__/challenge.cpython-313.pyc
  backend/src/schemas/__pycache__/user.cpython-313.pyc
  backend/src/server.py
  frontend/src/Inicio.js
  m-gym.db
Labels: documentation, enhancement

#98 Felipe#63
  backend/src/__pycache__/auth.cpython-313.pyc
  backend/src/__pycache__/database.cpython-313.pyc
  backend/src/__pycache__/server.cpython-313.pyc
  backend/src/models/__pycache__/__init__.cpython-313.pyc
  backend/src/models/__pycache__/activity.cpython-313.pyc
  backend/src/models/__pycache__/challenge.cpython-313.pyc
  backend/src/models/__pycache__/challengecompletion.cpython-313.pyc
  backend/src/models/__pycache__/profile.cpython-313.pyc
  backend/src/models/__pycache__/user.cpython-313.pyc
  backend/src/models/challengecompletion.py
  backend/src/schemas/__pycache__/activity.cpython-313.pyc
  backend/src/schemas/__pycache__/challenge.cpython-313.pyc
  backend/src/schemas/__pycache__/user.cpython-313.pyc
  backend/src/server.py
  frontend/src/CreateChallenge.js
  frontend/src/Inicio.js
  m-gym.db
Labels: enhancement

#99 Validação concluída close#68
  backend/src/__pycache__/auth.cpython-313.pyc
  backend/src/__pycache__/database.cpython-313.pyc
  backend/src/__pycache__/server.cpython-313.pyc
  backend/src/models/__pycache__/__init__.cpython-313.pyc
  backend/src/models/__pycache__/activity.cpython-313.pyc
  backend/src/models/__pycache__/challenge.cpython-313.pyc
  backend/src/models/__pycache__/challengecompletion.cpython-313.pyc
  backend/src/models/__pycache__/profile.cpython-313.pyc
  backend/src/models/__pycache__/user.cpython-313.pyc
  backend/src/schemas/__pycache__/activity.cpython-313.pyc
  backend/src/schemas/__pycache__/challenge.cpython-313.pyc
  backend/src/schemas/__pycache__/user.cpython-313.pyc
  frontend/src/Inicio.js
  m-gym.db
Labels: enhancement, help wanted

#101 Pedro#71
  backend/src/__pycache__/auth.cpython-313.pyc
  backend/src/__pycache__/database.cpython-313.pyc
  backend/src/__pycache__/server.cpython-313.pyc
  backend/src/models/__pycache__/__init__.cpython-313.pyc
  backend/src/models/__pycache__/activity.cpython-313.pyc
  backend/src/models/__pycache__/challenge.cpython-313.pyc
  backend/src/models/__pycache__/challengecompletion.cpython-313.pyc
  backend/src/models/__pycache__/profile.cpython-313.pyc
  backend/src/models/__pycache__/user.cpython-313.pyc
  backend/src/schemas/__pycache__/activity.cpython-313.pyc
  backend/src/schemas/__pycache__/challenge.cpython-313.pyc
  backend/src/schemas/__pycache__/challengecomplete.cpython-313.pyc
  backend/src/schemas/__pycache__/user.cpython-313.pyc
  backend/src/schemas/activity.py
  backend/src/schemas/challengecomplete.py
  backend/src/server.py
  frontend/src/Inicio.js
  m-gym.db
Labels: documentation, enhancement

#102 configurações para TDD em ambiente virtual. Testes de todas as rotas backend
  backend/m-gym.db
  backend/pytest.ini
  backend/requirements.txt
  backend/src/__pycache__/auth.cpython-313.pyc
  backend/src/__pycache__/database.cpython-313.pyc
  backend/src/__pycache__/init_db.cpython-313.pyc
  backend/src/__pycache__/server.cpython-313.pyc
  backend/src/models/__pycache__/__init__.cpython-313.pyc
  backend/src/models/__pycache__/activity.cpython-313.pyc
  backend/src/models/__pycache__/challenge.cpython-313.pyc
  backend/src/models/__pycache__/challengecompletion.cpython-313.pyc
  backend/src/models/__pycache__/profile.cpython-313.pyc
  backend/src/models/__pycache__/user.cpython-313.pyc
  backend/src/schemas/__pycache__/activity.cpython-313.pyc
  backend/src/schemas/__pycache__/challenge.cpython-313.pyc
  backend/src/schemas/__pycache__/challengecomplete.cpython-313.pyc
  backend/src/schemas/__pycache__/user.cpython-313.pyc
  backend/test.db
  backend/tests/__init__.py
  backend/tests/__pycache__/__init__.cpython-313.pyc
  backend/tests/__pycache__/conftest.cpython-313-pytest-8.4.1.pyc
  backend/tests/__pycache__/test_atividade_listar_meusDesafios.cpython-313-pytest-8.4.1.pyc
  backend/tests/__pycache__/test_atividadesDesafiosHistorico.cpython-313-pytest-8.4.1.pyc
  backend/tests/__pycache__/test_atualizaLoginSenha.cpython-313-pytest-8.4.1.pyc
  backend/tests/__pycache__/test_auth.cpython-313-pytest-8.4.1.pyc
  backend/tests/__pycache__/test_desafios.cpython-313-pytest-8.4.1.pyc
  backend/tests/__pycache__/test_get_profile.cpython-313-pytest-8.4.1.pyc
  backend/tests/__pycache__/test_listarRankingDesafioseRegistrarParticipacao.cpython-313-pytest-8.4.1.pyc
  backend/tests/__pycache__/test_tdd_backend.cpython-313-pytest-8.4.1.pyc
  backend/tests/conftest.py
  backend/tests/test_atividade_listar_meusDesafios.py
  backend/tests/test_atividadesDesafiosHistorico.py
  backend/tests/test_atualizaLoginSenha.py
  backend/tests/test_auth.py
  backend/tests/test_desafios.py
  backend/tests/test_get_profile.py
  backend/tests/test_listarRankingDesafioseRegistrarParticipacao.py
  frontend/jest.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Inicio.test.js
  frontend/src/Login.test.js
Labels: enhancement

#103 Pedro bugs finais
  backend/requirements.txt
  backend/src/__pycache__/server.cpython-313.pyc
  backend/src/server.py
  backend/test.db
  backend/tests/__pycache__/__init__.cpython-313.pyc
  backend/tests/__pycache__/conftest.cpython-313-pytest-8.4.1.pyc
  backend/tests/__pycache__/test_atividade_listar_meusDesafios.cpython-313-pytest-8.4.1.pyc
  backend/tests/__pycache__/test_atividadesDesafiosHistorico.cpython-313-pytest-8.4.1.pyc
  backend/tests/__pycache__/test_atualizaLoginSenha.cpython-313-pytest-8.4.1.pyc
  backend/tests/__pycache__/test_auth.cpython-313-pytest-8.4.1.pyc
  backend/tests/__pycache__/test_desafios.cpython-313-pytest-8.4.1.pyc
  backend/tests/__pycache__/test_get_profile.cpython-313-pytest-8.4.1.pyc
  backend/tests/__pycache__/test_listarRankingDesafioseRegistrarParticipacao.cpython-313-pytest-8.4.1.pyc
  backend/tests/test_atividade_listar_meusDesafios.py
  frontend/src/Inicio.js
  m-gym.db
Labels: bug
