Repository ES2-UFPI/m-Gym, pull requests merged in 2025-05, with the labels that each got.

#29 Validação de campos de usuário
  frontend/src/components/Form.js
Labels: documentation

#32 Pedro#7
  backend/server.js
  backend/src/__pycache__/server.cpython-312.pyc
  backend/src/schemas/__pycache__/user.cpython-312.pyc
  backend/src/schemas/user.py
  backend/src/server.py
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/Login.js
  frontend/src/Register.js
  package-lock.json
Labels: documentation, enhancement

#33 close #10 garantindo a unicidade do email no cadastro do usuário
  backend/src/__pycache__/database.cpython-312.pyc
  backend/src/__pycache__/database.cpython-313.pyc
  backend/src/__pycache__/server.cpython-312.pyc
  backend/src/__pycache__/server.cpython-313.pyc
  backend/src/database.py
  backend/src/init_db.py
  backend/src/models/__pycache__/user.cpython-312.pyc
  backend/src/models/__pycache__/user.cpython-313.pyc
  backend/src/models/user.py
  backend/src/schemas/__pycache__/user.cpython-312.pyc
  backend/src/schemas/__pycache__/user.cpython-313.pyc
  backend/src/schemas/user.py
  backend/src/server.py
  m-gym.db
Labels: enhancement, help wanted

#36 adaptação do código para criação de endpoint post /login e autenticação com JWT /session
  backend/requirements.txt
  backend/src/__pycache__/auth.cpython-313.pyc
  backend/src/__pycache__/database.cpython-313.pyc
  backend/src/__pycache__/server.cpython-313.pyc
  backend/src/auth.py
  backend/src/database.py
  backend/src/models/__pycache__/user.cpython-313.pyc
  backend/src/schemas/__pycache__/user.cpython-313.pyc
  backend/src/schemas/user.py
  backend/src/server.py
  m-gym.db
Labels: enhancement
